name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Server
      - run: ./ci/install_server.sh
  build:
    needs: setup
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        CUDA_INSTALL_DIR: /usr/local/cuda-10.2
      run: cargo build --verbose
    
