name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - run: ./ci/install_server.sh
  build:
    needs: setup
    runs-on: ubuntu-18.04
    env:
      CUDA_INSTALL_DIR: /usr/local/cuda-10.2
    steps:
      - run: cargo build
